- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: "{{ base_apt_cache_time }}"
  tags: ["update-apt-cache"]

- name: Install base packages
  apt:
    name: "{{ base_apt_packages }}"
    state: present

- name: Install additional packages
  apt:
    name: "{{ base_apt_packages_addons }}"
    state: present
