- name: Install passwd-init script
  template:
    src: passwd-init.j2
    dest: /usr/local/sbin/passwd-init
    mode: 0755
    group: root
    owner: root

- name: Install sudoers config to run passwd-init without password
  template:
    src: passwd-init_sudoers.j2
    dest: /etc/sudoers.d/passwd-init
    mode: 0440
    group: root
    owner: root
