- name: Deploys sshd config
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config.d/00-base.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - Reload sshd

- name: Removes old sshd config (ignored by sshd, no .conf suffix)
  file:
    path: /etc/ssh/sshd_config.d/base
    state: absent

- name: Configure authorized SSH keys
  authorized_key:
    user: "{{ item.name }}"
    key: "{{ item.ssh_keys | default([]) | join('\n') }}"
    state: present
    exclusive: True
  loop: "{{ base_users }}"
